sudo: required
services:
  - docker

before_install:
  - docker build -t sandeep/docker-react-pract -f Dockerfile.dev .

script:
  - docker run -e CI=true sandeep/docker-react-pract npm run test

deploy:
  provider: azure_web_apps
  verbose: true
  site: DockerReact
  username: sansanvi
  password: Sanvi12$$
  skip_cleanup: true
  on:
    branch: master